---
abstract: 'CBOR serializer for Dancer2'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Dancer2: 0.154000
  Dancer2::Logger::Console: 0
  File::Spec: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IPC::Open3: 0
  Plack::Test: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Serializer-CBOR
no_index:
  file:
    - README.pod
requires:
  CBOR::XS: 0
  Dancer2: 0.154000
  Dancer2::Core::Role::Serializer: 0
  Moo: 0
resources:
  bugtracker: http://github.com/PerlDancer/dancer2-serializer-cbor/issues
  repository: http://github.com/PerlDancer/dancer2-serializer-cbor
version: 0.000001
